### ISSUE TITLE
The evaluation code doesn't sort cell predictions by confidence score

### ISSUE THREAD

**Issue by youngjinshin** [lunit-io/ocelot23algo#5]
In this link (<https://ocelot2023.grand-challenge.org/evaluation-metric/>),
<img width="785" alt="image" src="https://github.com/lunit-io/ocelot23algo/assets/33065208/d4091dbd-b8c9-4571-b4cf-31b487ea94c7">

And following code is getting `confidence` from `pred_cls` in the function `_preprocess_distance_and_confidence`.

https://github.com/lunit-io/ocelot23algo/blob/fc3b470e256fc19fd41c22aa8a90cb01e89145c0/evaluation/eval.py#L123

In this code, `pred_cls` consists of `x`, `y`, `cls`, `prob`. It means `pred_cls[:, 2]` is an array of `cls`, not an array of `prob`.
The function `_calc_scores` uses this `cls` values to sort cell predictions.
https://github.com/lunit-io/ocelot23algo/blob/fc3b470e256fc19fd41c22aa8a90cb01e89145c0/evaluation/eval.py#L164-L168

To work properly, `confidence = pred_cls[:, 2]` might be `confidence = pred_cls[:, 3]` to sort cell predictions by confidence score.

**Comment by Aavache** [comment]
Thank you very much @youngjinshin for finding this issue!.

We confirmed that this issue has no major impact on the actual score nonetheless it will be resolved for the final stage. Please refer to this [announcement](https://grand-challenge.org/forums/forum/ocelot-2023-cell-detection-from-cell-tissue-interaction-704/topic/minor-issue-in-the-evaluation-1659/).

**Comment by Aavache** [comment]
Solved in https://github.com/lunit-io/ocelot23algo/pull/6, cheers!
